//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RideShareWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderInfo
    {
        public string ride_id { get; set; }
        public string user_id { get; set; }
        public string start_location { get; set; }
        public string end_location { get; set; }
        public Nullable<System.TimeSpan> pick_time { get; set; }
        public string comments { get; set; }
        public Nullable<decimal> rating { get; set; }
    
        public virtual Ride Ride { get; set; }
        public virtual User User { get; set; }
    }
}
