//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RideShareWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public string vehicle_id { get; set; }
        public string user_id { get; set; }
        public string type { get; set; }
        public Nullable<int> available_seats { get; set; }
        public Nullable<decimal> fuel_consumption { get; set; }
        public Nullable<decimal> vehicle_rating { get; set; }
        public string comments { get; set; }
    
        public virtual User User { get; set; }
    }
}
